package com.currencyconverter.app.ui

enum class AppLanguage { HE, EN }

data class UiText(
    val appTitle: String,
    val refresh: String,
    val amountTitle: String,
    val changeBaseHint: String,
    val convertTo: String,
    val addCurrencies: String,
    val menu: String,
    val add: String,
    val remove: String,
    val setAsBase: String,
    val loadingRates: String,
    val enterAmount: String,
    val pickOneCurrency: String,
    val attribution: String,
    val retry: String,
    val pickerTitle: String,
    val pickerHint: String,
    val searchPlaceholder: String,
    val baseCurrency: String,
    val loadingStatus: String,
    val updateFailed: String,
    val liveRate: String,
    val mixedRate: String,
    val weekend: String,
    val marketClosed: String,
    val updatedAt: String,
    val everyMinute: String,
    val sourceLive: String,
    val sourceEcb: String,
    val sourceFred: String,
    val networkError: String,
    val genericError: String,
    val languageToggle: String
)

fun AppLanguage.texts(): UiText = when (this) {
    AppLanguage.HE -> UiText(
        appTitle = "ממיר מטבעות",
        refresh = "רענון",
        amountTitle = "סכום להמרה",
        changeBaseHint = "לחצו כאן או על התפריט לבחירת מטבעות",
        convertTo = "המר אל",
        addCurrencies = "הוספת מטבעות",
        menu = "מטבעות",
        add = "הוספה",
        remove = "הסרה",
        setAsBase = "הפוך למטבע מקור",
        loadingRates = "טוען שערי מטבע מ-exchangerate.dev…",
        enterAmount = "הקלידו סכום כדי לראות המרה לכל מטבע שנבחר",
        pickOneCurrency = "בחרו לפחות מטבע אחד כדי לראות המרה",
        attribution = "שערים מ-exchangerate.dev · לידיעה בלבד, לא לסליקה",
        retry = "נסו שוב",
        pickerTitle = "בחירת מטבעות",
        pickerHint = "סמנו מטבעות להמרה. לחיצה על הדגל תשנה את מטבע המקור.",
        searchPlaceholder = "חיפוש לפי שם או קוד",
        baseCurrency = "מטבע מקור",
        loadingStatus = "טוען שערי מטבע…",
        updateFailed = "עדכון נכשל · מציג שער אחרון מ-",
        liveRate = "שער חי",
        mixedRate = "שער מעורב",
        weekend = " · סוף שבוע",
        marketClosed = " · שוק סגור",
        updatedAt = "עודכן ב-",
        everyMinute = " · כל דקה במסך פתוח",
        sourceLive = "חי",
        sourceEcb = "יומי ECB",
        sourceFred = "יומי FRED",
        networkError = "שגיאת רשת",
        genericError = "לא ניתן לעדכן שערים כרגע",
        languageToggle = "English"
    )
    AppLanguage.EN -> UiText(
        appTitle = "Currency Converter",
        refresh = "Refresh",
        amountTitle = "Amount to convert",
        changeBaseHint = "Tap here or the menu to choose currencies",
        convertTo = "Convert to",
        addCurrencies = "Add currencies",
        menu = "Currencies",
        add = "Add",
        remove = "Remove",
        setAsBase = "Set as base currency",
        loadingRates = "Loading rates from exchangerate.dev…",
        enterAmount = "Enter an amount to see it in every selected currency",
        pickOneCurrency = "Select at least one currency to convert into",
        attribution = "Rates from exchangerate.dev · indicative only, not for settlement",
        retry = "Try again",
        pickerTitle = "Choose currencies",
        pickerHint = "Check the currencies to convert into. Tap a flag to change the base currency.",
        searchPlaceholder = "Search by name or code",
        baseCurrency = "base currency",
        loadingStatus = "Loading exchange rates…",
        updateFailed = "Update failed · showing last rate from ",
        liveRate = "live rate",
        mixedRate = "mixed rate",
        weekend = " · weekend",
        marketClosed = " · market closed",
        updatedAt = "Updated at ",
        everyMinute = " · every minute while open",
        sourceLive = "live",
        sourceEcb = "ECB daily",
        sourceFred = "FRED daily",
        networkError = "Network error",
        genericError = "Could not refresh rates right now",
        languageToggle = "עברית"
    )
}
